name: rust_image

on:
  workflow_dispatch:
    # Just run it
  pull_request:
    branches:
      - 'main'
    paths:
      - './Dockerfile.rust'
  push:
    branches: 
      - main
    paths:
      - './Dockerfile.rust'

env:
  BUILPACK_TAG: jammy
  RUST_VERSION: 1.61.0
  RUSTUP_VERSION: 1.24.3

jobs:
  ic-dev-base-image:
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GCP Registry
        uses: docker/login-action@v1 
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username:  ${{ secrets.GH_PKG_LOGIN }}
          password:  ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Building rust image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          context: .
          build-args: |
           RUST_VERSION=${{ env.RUST_VERSION}}
           RUSTUP_VERSION=${{ env.RUSTUP_VERSION }}
           BUILPACK_TAG=${{ env.BUILPACK_TAG }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ci-rust:latest
            ghcr.io/${{ github.repository_owner }}/ci-rust:${{ env.BUILPACK_TAG }}-${{ env.RUST_VERSION }}
          file: ./Dockerfile.rust
