name: ic_dev_full_image

on:
  workflow_dispatch:
    # Just run it
  workflow_run:
    workflows: [rust_dfx_base_image, ic_binaries]
    types:
      - completed
  pull_request:
    branches:
      - 'main'
    paths:
      - 'ic-dev/Dockerfile.full'
  push:
    branches:
      - main
    paths:
      - 'ic-dev/Dockerfile.full'

env:
  BUILD_TAG: latest

jobs:
  ic-full-image:
    if: ${{ ! github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GCP Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PKG_LOGIN }}
          password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Full image"
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          context: ./ic-dev
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
            IC_BIN_IMAGE=ghcr.io/${{ github.repository_owner }}/ic-bin:latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/ic-dev-full:latest
            ghcr.io/${{ github.repository_owner }}/ic-dev-full:${{ env.BUILD_TAG }}
            us-central1-docker.pkg.dev/dfx-server/ci/ic-dev-full:latest
            us-central1-docker.pkg.dev/dfx-server/ci/ic-dev-full:${{ env.BUILD_TAG }}
          file: 'ic-dev/Dockerfile.full'
